add user's authorization
htmlacademy-react/345491-what-to-watch-7 pull request #11
Opened 2021-06-28 16:24 UTC by methanol

2021-06-29 11:17 UTC, klimnikova requested changes

2021-06-29 11:17 UTC, klimnikova commented on project/src/store/api-actions.js
> +    .catch(() => {
а тут что? ошибку надо обработать

2021-06-29 11:17 UTC, klimnikova commented on project/src/store/api-actions.js
> +    .then(() => dispatch(requireAuthorization(AuthorizationStatus.AUTH)))
аналогично - обработать ошибку

2021-07-02 12:25 UTC, klimnikova requested changes
может, ты забыл что-то запушить?

2021-07-02 12:25 UTC, klimnikova commented on project/src/components/pages/main-page/main-page.jsx
> +      {/* <ToastContainer
закомментированный код надо убрать

2021-07-02 12:25 UTC, klimnikova commented on project/src/components/pages/main-page/main-page.jsx
> +  // errorAction() {
аналогично

2021-07-02 12:25 UTC, klimnikova commented on project/src/store/api-actions.jsx
> +    // .catch(() => {dispatch(handleNetworkError());
закомментированный код

2021-07-02 12:25 UTC, klimnikova commented on project/src/store/api-actions.jsx
> +    // })
не увидела обработки ошибки в catch блоки

2021-07-07 09:44 UTC, klimnikova approved these changes

2021-07-07 09:44 UTC, klimnikova commented on project/src/components/pages/review-page/review-form/review-form.jsx
> +    const isMessageValid = (userReview.comment.length >= 50 && userReview.comment.length <= 400);
50 и 400 нужно вынести в константу

2021-07-07 09:44 UTC, merged

2021-07-08 06:44 UTC, methanol commented on project/src/components/pages/review-page/review-form/review-form.jsx
> +    const isMessageValid = (userReview.comment.length >= 50 && userReview.comment.length <= 400);
исправил

2021-07-08 06:44 UTC, methanol commented on project/src/store/actions.js
> +// export function handleNetworkError() {
исправил