Начинаем программировать
htmlacademy-react/345491-what-to-watch-7 pull request #3
Opened 2021-06-02 15:37 UTC by methanol

---
:mortar_board: [Начинаем программировать](https://up.htmlacademy.ru/react/7/user/345491/tasks/3)

2021-06-03 11:05 UTC, klimnikova requested changes
Надо вынести свг и дописать defaultProps, если они нужны. Может, стоит сделать объект обязательным?

2021-06-03 11:05 UTC, klimnikova commented on project/src/components/main-page/main-page.jsx
> +}
можно заменить все одной строчкой:
`Array.from(Array(20).keys())`

2021-06-03 14:18 UTC, methanol commented on project/src/components/app/app.jsx
> +  }),
добавил isRequired для объекта, если правильно понял defaultProps теперь можно не добавлять

2021-06-03 14:18 UTC, methanol commented on project/src/components/main-page/main-page.jsx
> +        <svg xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink">
вынес описание свг картинок в отдельный компонент

2021-06-03 14:19 UTC, methanol commented on project/src/components/main-page/main-page.jsx
> +              <a href="#" className="catalog__genres-link">Comedies</a>
вынес в отдельную функцию создание списка жанров

2021-06-03 14:20 UTC, methanol commented on project/src/components/main-page/main-page.jsx
> +}
заменил

2021-06-04 00:48 UTC, klimnikova commented on project/src/components/main-page/main-page.jsx
> +  const activeGenreIndex = 0;
обычно их называют renderGenresList

2021-06-04 00:49 UTC, klimnikova commented on project/src/components/main-page/main-page.jsx
> +    <li className= {ind === activeGenreIndex ? 'catalog__genres-item catalog__genres-item--active' : 'catalog__genres-item'} key = {it}>
здесь можно посмотреть в сторону пакета classnames

2021-06-04 00:50 UTC, klimnikova approved these changes
теперь все отлично!

2021-06-04 00:50 UTC, merged