Module4 task2
htmlacademy-react/345491-what-to-watch-7 pull request #7
Opened 2021-06-18 07:33 UTC by methanol

2021-06-18 08:15 UTC, klimnikova requested changes

2021-06-18 08:15 UTC, klimnikova commented on project/public/index.html
>  </head>
не надо так делать, ты теперь подключаешь не минифицированные стили. Если хочешь делать какие-то правки в стилях в этом проекте, то подключай файлики .css

2021-06-18 08:15 UTC, klimnikova commented on project/src/components/common-blocks/movie-tabs/movie-tabs.jsx
> +      <li className= {ind === activeOptionIndex ? 'film-nav__item film-nav__item--active' : 'film-nav__item'} key = {it} onClick = {() => setActiveOption(ind)}>
лучше использовать пакет classnames

2021-06-19 10:18 UTC, methanol commented on project/public/index.html
>  </head>
исправил

2021-06-19 10:19 UTC, methanol commented on project/src/components/common-blocks/movie-tabs/movie-tabs.jsx
> +      <li className= {ind === activeOptionIndex ? 'film-nav__item film-nav__item--active' : 'film-nav__item'} key = {it} onClick = {() => setActiveOption(ind)}>
исправил

2021-06-19 10:43 UTC, klimnikova requested changes
надо по-другому импортировать classnames

2021-06-19 10:43 UTC, klimnikova commented on project/src/components/common-blocks/movie-tabs/movie-tabs.jsx
> +const classNames = require('classnames');
так в реакте не делаем, тут ES модули. Вообще очень странно, что у тебя все работает и линтер не ругается. 
Такое объявление только в NodeJS

2021-06-19 10:43 UTC, klimnikova commented on project/public/css/main.css
>    .film-card--full {
в этом файле правки забыл убрать, видимо

2021-06-19 12:32 UTC, methanol commented on project/src/components/common-blocks/movie-tabs/movie-tabs.jsx
> +const classNames = require('classnames');
исправил, причем и еще в одном месте где ты не заметила)

2021-06-19 12:32 UTC, methanol commented on project/public/css/main.css
>    .film-card--full {
если ты про background, то она там не нужен, так как теперь подключается динамически для каждого фильма

2021-06-20 06:52 UTC, klimnikova approved these changes

2021-06-20 06:52 UTC, klimnikova commented on project/package.json
>      "axios": "^0.21.1",
а где зависимость classnames? надо установить пакет в проект, если ты хочешь, им пользоваться в своем коде

2021-06-20 06:52 UTC, merged